from enum import Enum


class Permission(str, Enum):
    CONFIGURE_SYSTEM = "CONFIGURE_SYSTEM"
    MANAGE_TECHNICAL = "MANAGE_TECHNICAL"
    REVIEW_KNOWLEDGE = "REVIEW_KNOWLEDGE"
    APPROVE_KNOWLEDGE = "APPROVE_KNOWLEDGE"
    REJECT_KNOWLEDGE = "REJECT_KNOWLEDGE"
    CREATE_CANDIDATE = "CREATE_CANDIDATE"
    PROPOSE_CHANGE = "PROPOSE_CHANGE"
    READ_KNOWLEDGE = "READ_KNOWLEDGE"
