from enum import Enum


class Role(str, Enum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    KNOWLEDGE_REVIEWER = "KNOWLEDGE_REVIEWER"
    KNOWLEDGE_PRODUCER = "KNOWLEDGE_PRODUCER"
    READ_ONLY_USER = "READ_ONLY_USER"
